/** @type {import('postcss-load-config').Config} */
const config = {
    plugins: {
        'postcss-mixins': {
            mixins: {
                'h1-text': {
                    'font-family': 'Work Sans, sans-serif',
                    'font-size': 'var(--font-size-h1)',
                    'font-weight': '600',
                    'line-height': '1.2',
                    'letter-spacing': '-0.02em',
                    'color': 'var(--color-h1)',
                    'margin': '0 0 1.5rem',
                },
                'h2-text': {
                    'font-family': 'Work Sans, sans-serif',
                    'font-size': 'var(--font-size-h2)',
                    'font-weight': '600',
                    'line-height': '1.2',
                    'letter-spacing': '-0.02em',
                    'color': 'var(--color-h2)',
                    'margin': '0 0 1.5rem',
                },
                'h3-text': {
                    'font-family': 'Work Sans, sans-serif',
                    'font-size': 'var(--font-size-h3)',
                    'font-weight': '600',
                    'line-height': '1.2',
                    'letter-spacing': '-0.02em',
                    'color': 'var(--color-h3)',
                    'margin': '0 0 1.5rem',
                },
                'h4-text': {
                    'font-family': 'Work Sans, sans-serif',
                    'font-size': 'var(--font-size-h4)',
                    'font-weight': '500',
                    'line-height': '1.2',
                    'letter-spacing': '-0.02em',
                    'color': 'var(--color-h4)',
                    'margin': '0 0 1.5rem',
                },
                'h5-text': {
                    'font-family': 'Work Sans, sans-serif',
                    'font-size': 'var(--font-size-h5)',
                    'font-weight': '500',
                    'line-height': '1.2',
                    'letter-spacing': '-0.02em',
                    'color': 'var(--color-h5)',
                    'margin': '0 0 1.5rem',
                },
                'body-text': {
                    'font-family': 'Mozilla Headline, sans-serif',
                    'font-size': 'var(--font-size-body)',
                    'font-weight': '300',
                    'line-height': '1.5',
                    'letter-spacing': '-0.02em',
                    'color': 'var(--color-body)',
                    'margin': '0 0 1.5rem',
                },
                'body-text-sm': {
                    'font-family': 'Mozilla Headline, sans-serif',
                    'font-size': 'var(--font-size-body-sm)',
                    'font-weight': '300',
                    'line-height': '1.5',
                },
                'button-text': {
                    'font-family': 'Work Sans, sans-serif',
                    'font-size': '0.975rem',
                    'font-weight': '400',
                    'line-height': '1.5',
                },
                'dropdown-button-text': {
                    'font-family': 'Mozilla Headline, sans-serif',
                    'font-size': '0.675rem',
                    'font-weight': '300',
                    'line-height': '1.5',
                },
                'button-primary': {
                    'font-family': 'Work Sans, sans-serif',
                    'font-size': '0.975rem',
                    'padding': '0.75rem 2rem',
                    'background-color': 'var(--button-primary)',
                    'color': 'var(--button-primary-foreground)',
                    'border-radius': '0.5rem',
                    'font-weight': '600',
                },

                'button-primary': {
                    'font-family': 'Work Sans, sans-serif',
                    'background-color': 'oklch(0.17 0.03 287.64)',
                    'color': '#abbedf',
                    'box-shadow': 'inset 0px 0px 3px 0px oklch(0.54 0.12 247.05 / 0.23)',
                    'font-weight': '400',
                    'line-height': '0',
                    'display': 'inline-flex',
                    'align-items': 'center',
                    'height': '2.5rem',
                    'justify-content': 'center',
                    'gap': '.5rem',
                    'font-weight': '500',
                    'white-space': 'nowrap',
                    'padding': '1.75rem 2rem',
                    'border-radius': '.5rem',
                    'cursor': 'pointer',
                    'transition': 'background-color .2s ease-in-out, color .2s ease-in-out',
                    'font-size': '15px !important',
                    'outline': '1px solid oklch(0.28 0.02 269.94) !important',
                },
                'button-primary-hover': {
                    'background-color': 'var(--button-primary-hover)',
                    'color': 'var(--button-primary-foreground-hover)',
                },
                'input-text': {
                    'background-color': 'oklch(0.45 0.03 293.43)',
                    'box-shadow': 'inset 1px 2px 1px 2px oklch(0.31 0.0122 258.37 / 0.92)',
                    'border': 'oklch(.215 .14 215.14 / .5)',
                    'border-radius': '0.5rem !important',
                    'padding': '0.5rem !important',
                    'margin': '0.5rem !important',
                    'font-size': '1rem !important',
                    'background': 'oklch(0.3 0.03 269.92 / 0.5)',
                    'box-shadow': 'inset -2px 2px 2px 1px oklch(0.18 0 0)',
                    'border': '1px solid #5d5562',
                    'border-radius': '0.5rem !important',
                    'padding': '0.8rem !important',
                    'margin': '0.5rem !important',
                    'font-size': '0.8rem !important',
                    'color': '#f4f6f8',
                    'width': '100% !important',
                    'margin-left': '0px !important',
                    'font-weight': '500 !important',
                    'line-height': '1.5 !important',
                },
                'input-textarea': {
                    'background': 'oklch(0.3 0.03 269.92 / 0.5)',
                    'box-shadow': 'inset -2px 2px 2px 1px oklch(0.18 0 0)',
                    'border': '1px solid #5d5562',
                    'border-radius': '0.5rem !important',
                    'padding': '0.8rem !important',
                    'margin': '0.5rem !important',
                    'font-size': '0.8rem !important',
                    'color': '#f4f6f8',
                    'width': '100% !important',
                    'margin-left': '0px !important',
                    'font-weight': '500 !important',
                    'line-height': '1.5 !important',
                },
            },
        },
        'postcss-utilities': {},
        'tailwindcss': {},
    },
};

export default config;