// Import Prisma's generated types
import type { Bundle, BundlePodcast, Episode, EpisodeFeedback, FeedbackRating, Notification, Podcast, ProfilePodcast, Subscription, User, UserCurationProfile } from "@prisma/client"

// Re-export all Prisma types for convenience
export type { User, UserCurationProfile, Podcast, Bundle, Episode, BundlePodcast, ProfilePodcast, Notification, Subscription, EpisodeFeedback, FeedbackRating }

// Only keep custom types that can't be generated by Prisma
export interface FormState {
	success: boolean
	message: string
}
