// Import Prisma's generated types
import type { Bundle, BundlePodcast, Episode, EpisodeFeedback, FeedbackRating, Notification, Podcast, ProfilePodcast, Subscription, User, UserCurationProfile } from "@prisma/client"

// Re-export all Prisma types for convenience
export type { User, UserCurationProfile, Podcast, Bundle, Episode, BundlePodcast, ProfilePodcast, Notification, Subscription, EpisodeFeedback, FeedbackRating }

// Custom types that combine Prisma types with relations
export type UserCurationProfileWithRelations = UserCurationProfile & {
	selectedBundle?: (Bundle & { podcasts: Podcast[]; episodes: Episode[] }) | null
	episode: Episode[]
}

// Source type for podcast sources
export interface Source {
	id: string
	name: string
	url: string
	image_url?: string
}

// Only keep custom types that can't be generated by Prisma
export interface FormState {
	success: boolean
	message: string
}
